name: ${project.artifactId}
main: com.jaoafa.MinecraftJPVoteMissFiller.Main
version: ${project.version}
description: MinecraftJapanServersで多発している投票受信失敗の対応用のプラグイン。
database: true
author: mine_book000
softdepend: [Votifier, DiscordMC]
website: https://jaoafa.com/
